apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  version: 7.10.1
  nodeSets:
    - name: default
      #      config:
      #        node.store.allow_mmap: false
      podTemplate:
        metadata:
          name: elasticsearch
          labels:
            app: elasticsearch
        spec:
          # Allow virtual memory mapping
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              securityContext:
                capabilities:
                  add: ["SYS_CHROOT"]
              resources:
                limits:
                  # Must be more than twice the value jvm used
                  cpu: 1500m
                  memory: 2Gi
                requests:
                  cpu: 200m
                  memory: 1Gi
              env:
                - name: ES_JAVA_OPTS
                  # Currently there are bugs if we assign mem more than 8g
                  value: "-Xms1g -Xmx1g"
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
            labels:
              app: elasticsearch
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                # NFS is used and NFS provisioner doesn't restrict the size of the pv
                storage: 1Mi
            storageClassName: nfs-client-eck
