apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  version: 7.10.1
  nodeSets:
    - name: default
      config:
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          name: elasticsearch
          labels:
            app: elasticsearch
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 5Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
            labels:
              app: elasticsearch
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: nfs-client
