apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  labels:
    app: {{ template "eck.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  version: 7.10.1
  nodeSets:
    - name: default
      labels:
        app: {{ template "eck.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
      config:
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          labels:
            plm-tag: plm-es
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 4Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
            labels:
              app: {{ template "eck.name" . }}
              chart: {{ .Chart.Name }}-{{ .Chart.Version }}
              heritage: {{ .Release.Service }}
              release: {{ .Release.Name }}
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: nfs-client
